import { createFileRoute } from "@tanstack/react-router";
import type { ReactElement } from "react";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { PageHeader } from "@/components/CrudPage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { fmtDate, fmtDateTime, fmtMoney, todayISO } from "@/lib/format";
import { toast } from "sonner";
import { Download, FileText, Printer, Search, Trash2 } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export const Route = createFileRoute("/_authenticated/cash-flow")({
  ssr: false,
  head: () => ({ meta: [{ title: "Cash Flow — Novza ERP" }] }),
  component: CashFlowPage,
});

type Tx = {
  id: string; operation_type: "income" | "expense"; operation_date: string; amount: number; usd_rate: number | null;
  amount_uzs: number | null; account_id: string; contragent_id: string | null; source_id: string | null; employee_id: string | null;
  charge_type_id: string | null; note: string | null; created_at: string; zayavka_number: string | null; operation_number?: string | null;
  cash_flow_category?: string | null; branch?: string | null; status?: string | null; created_by_name?: string | null; approved_by?: string | null;
};
type Expected = { id: string; payment_type: string; due_date: string; amount: number; currency: "UZS" | "USD"; amount_uzs: number | null; category: string; status: string; counterparty: string | null; note: string | null };
type Audit = { id: number; table_name: string; record_id: string | null; action: string; old_data: unknown; new_data: unknown; created_at: string };
const cats = ["Savdo", "Xarid", "Oylik", "Avans", "Bonus", "Jarima", "Soliq", "Kommunal", "Kredit", "Qarz", "Boshqa"];

function CashFlowPage() {
  const qc = useQueryClient();
  const [selected, setSelected] = useState<string[]>([]);
  const [page, setPage] = useState(1);
  const [filters, setFilters] = useState({ range: "month", from: "", to: "", account: "all", category: "all", type: "all", search: "", branch: "all" });
  const pageSize = 25;

  const { data: accounts = [] } = useQuery({ queryKey: ["cf_accounts"], queryFn: async () => (await supabase.from("accounts").select("id,name,currency")).data ?? [] });
  const { data: refs = { contragent: {}, source: {}, employee: {}, charge: {} } } = useQuery({
    queryKey: ["cf_refs"],
    queryFn: async () => {
      const [c, s, e, ch] = await Promise.all([
        supabase.from("contragents").select("id,name"), supabase.from("sources").select("id,name"),
        supabase.from("employees").select("id,full_name"), supabase.from("charge_types").select("id,name"),
      ]);
      return {
        contragent: Object.fromEntries((c.data ?? []).map((x) => [x.id, x.name])), source: Object.fromEntries((s.data ?? []).map((x) => [x.id, x.name])),
        employee: Object.fromEntries((e.data ?? []).map((x) => [x.id, x.full_name])), charge: Object.fromEntries((ch.data ?? []).map((x) => [x.id, x.name])),
      } as Record<string, Record<string, string>>;
    },
  });
  const { data: txs = [] } = useQuery({ queryKey: ["cf_txs"], queryFn: async () => ((await supabase.from("transactions").select("*").order("operation_date", { ascending: false }).limit(3000)).data ?? []) as Tx[] });
  const { data: expected = [] } = useQuery({ queryKey: ["cf_expected"], queryFn: async () => ((await supabase.from("cash_flow_expected_payments" as never).select("*").order("due_date", { ascending: true })).data ?? []) as Expected[] });
  const { data: audit = [] } = useQuery({ queryKey: ["cf_audit"], queryFn: async () => ((await supabase.from("audit_log").select("*").in("table_name", ["transactions", "cash_flow_expected_payments"]).order("created_at", { ascending: false }).limit(100)).data ?? []) as Audit[] });

  const lookupAccount = Object.fromEntries(accounts.map((a) => [a.id, a]));
  const period = getPeriod(filters.range, filters.from, filters.to);
  const rows = useMemo(() => txs.filter((t) => {
    const acc = lookupAccount[t.account_id]; const category = t.cash_flow_category || refs.source[t.source_id ?? ""] || refs.charge[t.charge_type_id ?? ""] || "Boshqa";
    const hay = [t.operation_number, t.zayavka_number, t.note, category, refs.contragent[t.contragent_id ?? ""], refs.employee[t.employee_id ?? ""], t.branch].join(" ").toLowerCase();
    return t.operation_date >= period.from && t.operation_date <= period.to && (filters.account === "all" || t.account_id === filters.account) && (filters.type === "all" || t.operation_type === filters.type) && (filters.category === "all" || category === filters.category) && (filters.branch === "all" || (t.branch || "Asosiy") === filters.branch) && (!filters.search || hay.includes(filters.search.toLowerCase()));
  }), [txs, filters, refs, period.from, period.to]);
  const branches = Array.from(new Set(txs.map((t) => t.branch || "Asosiy")));
  const today = todayISO();
  const sum = (a: Tx[], type?: "income" | "expense") => a.filter((x) => !type || x.operation_type === type).reduce((s, x) => s + Number(x.amount_uzs ?? x.amount), 0);
  const startBalance = sum(txs.filter((t) => t.operation_date < period.from && t.operation_type === "income")) - sum(txs.filter((t) => t.operation_date < period.from && t.operation_type === "expense"));
  const income = sum(rows, "income"), expense = sum(rows, "expense"), current = startBalance + income - expense;
  const expIn = expected.filter((e) => e.payment_type.includes("income") || e.payment_type.includes("receivable")).reduce((s, e) => s + Number(e.amount_uzs ?? e.amount), 0);
  const expOut = expected.filter((e) => e.payment_type.includes("expense") || e.payment_type.includes("payable")).reduce((s, e) => s + Number(e.amount_uzs ?? e.amount), 0);
  const kpis = [["Boshlang'ich qoldiq", startBalance], ["Joriy qoldiq", current], ["Bugungi kirim", sum(rows.filter((t) => t.operation_date === today), "income")], ["Bugungi chiqim", sum(rows.filter((t) => t.operation_date === today), "expense")], ["Oylik kirim", income], ["Oylik chiqim", expense], ["Sof pul oqimi", income - expense], ["Kutilayotgan kirim", expIn], ["Kutilayotgan chiqim", expOut], ["Prognoz qoldiq", current + expIn - expOut]];
  const daily = aggregate(rows, "day"), monthly = aggregate(rows, "month"), yearly = aggregate(rows, "year");
  const byAccount = accounts.map((a) => ({ name: a.name, kirim: sum(rows.filter((r) => r.account_id === a.id), "income"), chiqim: sum(rows.filter((r) => r.account_id === a.id), "expense") }));
  const byCategory = cats.map((c) => ({ name: c, kirim: sum(rows.filter((r) => (r.cash_flow_category || refs.source[r.source_id ?? ""] || "Boshqa") === c), "income"), chiqim: sum(rows.filter((r) => (r.cash_flow_category || refs.source[r.source_id ?? ""] || "Boshqa") === c), "expense") })).filter((x) => x.kirim || x.chiqim);
  const pageRows = rows.slice((page - 1) * pageSize, page * pageSize);
  const bulkDelete = useMutation({ mutationFn: async () => { const { error } = await supabase.from("transactions").delete().in("id", selected); if (error) throw error; }, onSuccess: () => { toast.success("Tanlanganlar o'chirildi"); setSelected([]); qc.invalidateQueries({ queryKey: ["cf_txs"] }); } });

  const exportExcel = async () => { const XLSX = await import("xlsx"); const ws = XLSX.utils.json_to_sheet(rows.map((r) => mapRow(r, lookupAccount, refs))); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Cash Flow"); XLSX.writeFile(wb, `cash_flow_${today}.xlsx`); };
  const exportPdf = async () => { const { jsPDF } = await import("jspdf"); const doc = new jsPDF({ orientation: "landscape" }); doc.text("Cash Flow hisoboti", 14, 14); rows.slice(0, 35).forEach((r, i) => doc.text(`${fmtDate(r.operation_date)}  ${r.operation_type === "income" ? "Kirim" : "Chiqim"}  ${fmtMoney(r.amount_uzs ?? r.amount)}  ${refs.contragent[r.contragent_id ?? ""] ?? ""}`, 14, 24 + i * 6)); doc.save(`cash_flow_${today}.pdf`); };

  return <><PageHeader title="💰 Cash Flow" description="Pul oqimlari, real-time tahlil, prognoz va Kassa integratsiyasi" />
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-4">{kpis.map(([l, v]) => <Card key={l as string}><CardContent className="p-3"><div className="text-xs text-muted-foreground">{l}</div><div className="text-lg font-semibold tabular-nums mt-1">{fmtMoney(v as number)}</div></CardContent></Card>)}</div>
    <Card className="mb-4"><CardContent className="p-3 grid grid-cols-2 md:grid-cols-7 gap-2"><Select value={filters.range} onValueChange={(v) => setFilters({ ...filters, range: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["today", "yesterday", "week", "month", "quarter", "year", "custom"].map((x) => <SelectItem key={x} value={x}>{labelRange(x)}</SelectItem>)}</SelectContent></Select><Input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value, range: "custom" })} /><Input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value, range: "custom" })} /><Select value={filters.account} onValueChange={(v) => setFilters({ ...filters, account: v })}><SelectTrigger><SelectValue placeholder="Hisob" /></SelectTrigger><SelectContent><SelectItem value="all">Barcha hisoblar</SelectItem>{accounts.map((a) => <SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select><Select value={filters.category} onValueChange={(v) => setFilters({ ...filters, category: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Barcha kategoriya</SelectItem>{cats.map((c) => <SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select><Select value={filters.branch} onValueChange={(v) => setFilters({ ...filters, branch: v })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Barcha filial</SelectItem>{branches.map((b) => <SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select><div className="relative"><Search className="size-4 absolute left-2 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input className="pl-8" placeholder="Qidiruv" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /></div></CardContent></Card>
    <Tabs defaultValue="dashboard"><TabsList className="mb-4 flex flex-wrap h-auto"><TabsTrigger value="dashboard">Dashboard</TabsTrigger><TabsTrigger value="ops">Operatsiyalar</TabsTrigger><TabsTrigger value="analytics">Analitika</TabsTrigger><TabsTrigger value="expected">Kutilayotgan</TabsTrigger><TabsTrigger value="forecast">Prognoz</TabsTrigger><TabsTrigger value="calendar">Kalendar</TabsTrigger><TabsTrigger value="audit">Audit Log</TabsTrigger></TabsList>
      <TabsContent value="dashboard"><div className="grid lg:grid-cols-2 gap-4"><ChartCard title="Kunlik Cash Flow"><AreaChart data={daily}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="period" /><YAxis /><Tooltip /><Area dataKey="kirim" stroke="var(--color-success)" fill="var(--color-success)" fillOpacity={0.2} /><Area dataKey="chiqim" stroke="var(--color-destructive)" fill="var(--color-destructive)" fillOpacity={0.15} /></AreaChart></ChartCard><ChartCard title="Oylik Cash Flow"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="period" /><YAxis /><Tooltip /><Bar dataKey="kirim" fill="var(--color-success)" /><Bar dataKey="chiqim" fill="var(--color-destructive)" /></BarChart></ChartCard><ChartCard title="Yillik Cash Flow"><LineChart data={yearly}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="period" /><YAxis /><Tooltip /><Line dataKey="sof" stroke="var(--color-primary)" /></LineChart></ChartCard><ChartCard title="Hisob raqamlar kesimida"><BarChart data={byAccount}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="kirim" fill="var(--color-chart-2)" /><Bar dataKey="chiqim" fill="var(--color-chart-4)" /></BarChart></ChartCard></div></TabsContent>
      <TabsContent value="ops"><Card><CardHeader className="flex flex-row justify-between"><CardTitle>Cash Flow operatsiyalari</CardTitle><div className="flex gap-2"><Button variant="outline" size="sm" onClick={exportExcel}><Download className="size-4 mr-1" />Excel</Button><Button variant="outline" size="sm" onClick={exportPdf}><FileText className="size-4 mr-1" />PDF</Button><Button variant="outline" size="sm" onClick={() => print()}><Printer className="size-4 mr-1" />Print</Button><Button variant="destructive" size="sm" disabled={!selected.length} onClick={() => bulkDelete.mutate()}><Trash2 className="size-4 mr-1" />Bulk Delete</Button></div></CardHeader><CardContent><DataTable rows={pageRows} selected={selected} setSelected={setSelected} lookupAccount={lookupAccount} refs={refs} /><div className="flex justify-end gap-2 mt-3"><Button variant="outline" size="sm" disabled={page === 1} onClick={() => setPage(page - 1)}>Oldingi</Button><Button variant="outline" size="sm" disabled={page * pageSize >= rows.length} onClick={() => setPage(page + 1)}>Keyingi</Button></div></CardContent></Card></TabsContent>
      <TabsContent value="analytics"><div className="grid lg:grid-cols-2 gap-4"><Report title="Kunlik" data={daily} /><Report title="Oylik" data={monthly} /><Report title="Kategoriya pivot" data={byCategory} /><Report title="Hisob raqami pivot" data={byAccount} /></div></TabsContent>
      <TabsContent value="expected"><Card><CardHeader><CardTitle>Kutilayotgan to'lovlar</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Sana</TableHead><TableHead>Turi</TableHead><TableHead>Summa</TableHead><TableHead>Kategoriya</TableHead><TableHead>Kontragent</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{expected.map((e) => <TableRow key={e.id}><TableCell>{fmtDate(e.due_date)}</TableCell><TableCell>{e.payment_type}</TableCell><TableCell>{fmtMoney(e.amount_uzs ?? e.amount, e.currency)}</TableCell><TableCell>{e.category}</TableCell><TableCell>{e.counterparty ?? "—"}</TableCell><TableCell><StatusBadge due={e.due_date} status={e.status} /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="forecast"><div className="grid md:grid-cols-4 gap-3">{[7, 30, 90, 365].map((d) => <Card key={d}><CardContent className="p-4"><div className="text-sm text-muted-foreground">{d === 365 ? "1 yillik" : `${d} kunlik`} prognoz</div><div className="text-xl font-semibold mt-2">{fmtMoney(current + (income - expense) / Math.max(1, daily.length) * d + expIn - expOut)}</div><Badge variant={current < expense / 2 ? "destructive" : "secondary"} className="mt-3">{current < expense / 2 ? "Pul yetishmovchiligi xavfi" : "Barqaror"}</Badge></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="calendar"><Calendar rows={rows} expected={expected} /></TabsContent><TabsContent value="audit"><Report title="Audit Log" data={audit.map((a) => ({ period: fmtDateTime(a.created_at), kirim: a.action, chiqim: a.table_name, sof: a.record_id ?? "—" }))} /></TabsContent>
    </Tabs></>;
}

function ChartCard({ title, children }: { title: string; children: ReactElement }) { return <Card><CardHeader><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></CardContent></Card>; }
function aggregate(rows: Tx[], mode: "day" | "month" | "year") { const m = new Map<string, { period: string; kirim: number; chiqim: number; sof: number; qoldiq: number }>(); rows.forEach((r) => { const p = mode === "day" ? r.operation_date : mode === "month" ? r.operation_date.slice(0, 7) : r.operation_date.slice(0, 4); const x = m.get(p) ?? { period: p, kirim: 0, chiqim: 0, sof: 0, qoldiq: 0 }; const v = Number(r.amount_uzs ?? r.amount); if (r.operation_type === "income") x.kirim += v; else x.chiqim += v; x.sof = x.kirim - x.chiqim; x.qoldiq += r.operation_type === "income" ? v : -v; m.set(p, x); }); return Array.from(m.values()).sort((a, b) => a.period.localeCompare(b.period)); }
function getPeriod(range: string, from: string, to: string) { const d = new Date(); const iso = (x: Date) => x.toISOString().slice(0, 10); const start = new Date(d); if (range === "today") return { from: iso(d), to: iso(d) }; if (range === "yesterday") { const y = new Date(d); y.setDate(y.getDate() - 1); return { from: iso(y), to: iso(y) }; } if (range === "week") start.setDate(d.getDate() - 7); else if (range === "quarter") start.setMonth(d.getMonth() - 3); else if (range === "year") start.setMonth(0, 1); else start.setDate(1); return range === "custom" ? { from: from || "1900-01-01", to: to || "2999-12-31" } : { from: iso(start), to: iso(d) }; }
function labelRange(x: string) { return ({ today: "Bugun", yesterday: "Kecha", week: "Shu hafta", month: "Shu oy", quarter: "Shu chorak", year: "Shu yil", custom: "Custom" } as Record<string, string>)[x]; }
function mapRow(r: Tx, accs: Record<string, { name: string; currency: string }>, refs: Record<string, Record<string, string>>) { const acc = accs[r.account_id]; return { Sana: r.operation_date, "Operatsiya raqami": r.operation_number ?? r.zayavka_number ?? r.id.slice(0, 8), Turi: r.operation_type === "income" ? "Kirim" : "Chiqim", Summa: Number(r.amount), Valyuta: acc?.currency ?? "UZS", Kurs: r.usd_rate ?? "", "Hisob raqami": acc?.name ?? "", Kontragent: refs.contragent[r.contragent_id ?? ""] ?? "", Kategoriya: r.cash_flow_category ?? refs.source[r.source_id ?? ""] ?? "Boshqa", Izoh: r.note ?? "", Yaratuvchi: r.created_by_name ?? "", Status: r.status ?? "completed", Tasdiqlovchi: r.approved_by ?? "" }; }
function DataTable({ rows, selected, setSelected, lookupAccount, refs }: { rows: Tx[]; selected: string[]; setSelected: (v: string[]) => void; lookupAccount: Record<string, { name: string; currency: string }>; refs: Record<string, Record<string, string>> }) { return <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead></TableHead>{["Sana", "Operatsiya raqami", "Kirim / Chiqim", "Summa", "Valyuta", "Kurs", "Hisob raqami", "Kontragent", "Kategoriya", "Izoh", "Yaratuvchi", "Status", "Tasdiqlovchi"].map((h) => <TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r) => { const acc = lookupAccount[r.account_id]; return <TableRow key={r.id}><TableCell><Checkbox checked={selected.includes(r.id)} onCheckedChange={(c) => setSelected(c ? [...selected, r.id] : selected.filter((x) => x !== r.id))} /></TableCell><TableCell>{fmtDate(r.operation_date)}</TableCell><TableCell className="font-mono">{r.operation_number ?? r.zayavka_number ?? r.id.slice(0, 8)}</TableCell><TableCell>{r.operation_type === "income" ? <Badge className="bg-success text-success-foreground">Kirim</Badge> : <Badge variant="destructive">Chiqim</Badge>}</TableCell><TableCell className="font-medium tabular-nums">{fmtMoney(r.amount, acc?.currency as "UZS" | "USD")}</TableCell><TableCell>{acc?.currency ?? "UZS"}</TableCell><TableCell>{r.usd_rate ?? "—"}</TableCell><TableCell>{acc?.name ?? "—"}</TableCell><TableCell>{refs.contragent[r.contragent_id ?? ""] ?? "—"}</TableCell><TableCell>{r.cash_flow_category ?? refs.source[r.source_id ?? ""] ?? "Boshqa"}</TableCell><TableCell className="max-w-48 truncate">{r.note ?? "—"}</TableCell><TableCell>{r.created_by_name ?? "Tizim"}</TableCell><TableCell>{r.status ?? "completed"}</TableCell><TableCell>{r.approved_by ?? "—"}</TableCell></TableRow>; })}</TableBody></Table></div>; }
function Report({ title, data }: { title: string; data: Record<string, unknown>[] }) { return <Card><CardHeader><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow>{Object.keys(data[0] ?? { period: "Davr", kirim: "Kirim", chiqim: "Chiqim", sof: "Sof oqim", qoldiq: "Qoldiq" }).map((k) => <TableHead key={k}>{k}</TableHead>)}</TableRow></TableHeader><TableBody>{data.map((r, i) => <TableRow key={i}>{Object.values(r).map((v, j) => <TableCell key={j}>{typeof v === "number" ? fmtMoney(v) : String(v)}</TableCell>)}</TableRow>)}</TableBody></Table></CardContent></Card>; }
function StatusBadge({ due, status }: { due: string; status: string }) { const days = Math.ceil((new Date(due).getTime() - Date.now()) / 86400000); const s = status === "completed" ? "Yakunlangan" : days < 0 ? "Muddati o'tgan" : days <= 3 ? "Yaqinlashmoqda" : "Normal"; return <Badge variant={s === "Muddati o'tgan" ? "destructive" : "secondary"}>{s}</Badge>; }
function Calendar({ rows, expected }: { rows: Tx[]; expected: Expected[] }) { const events = [...rows.slice(0, 80).map((r) => ({ d: r.operation_date, t: r.operation_type === "income" ? "Kirim" : "Chiqim", v: r.amount_uzs ?? r.amount, kind: r.operation_type })), ...expected.map((e) => ({ d: e.due_date, t: "Kutilayotgan", v: e.amount_uzs ?? e.amount, kind: "expected" }))]; return <div className="grid md:grid-cols-7 gap-2">{events.map((e, i) => <Card key={i} className="min-h-24"><CardContent className="p-3"><div className="text-xs text-muted-foreground">{fmtDate(e.d)}</div><Badge variant={e.kind === "expense" ? "destructive" : "secondary"} className="my-2">{e.t}</Badge><div className="text-sm font-semibold">{fmtMoney(e.v)}</div></CardContent></Card>)}</div>; }